# Generated by Django 4.2.5 on 2024-03-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="fees_paid",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
