# Generated by Django 4.2.5 on 2024-03-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_student_fees_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="fees_unpaid",
            field=models.IntegerField(default=60000),
        ),
    ]
