# Generated by Django 4.2.5 on 2024-03-11 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_student_fees_unpaid"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="college",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.college"
            ),
        ),
    ]
